version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api

    ports:
      - "8080:80"

    depends_on:
      - db

    volumes:
      - ./api:/var/www/ApiPlateform

  db:
    image: mariadb:10.8
    container_name: api_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sae401
      MYSQL_USER: sae401
      MYSQL_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: api_phpmyadmin
    ports:
      - 8082:80

  maildev:
    image: maildev/maildev
    container_name: maildev_symfony
    command: bin/maildev --web 80 --smtp 1025 --hide-extensions STARTTLS
    restart: always
    ports:
      - 8081:80